#+TITLE: dmenu

* Table of Contents :toc:
- [[#what-is-dmenu][What is dmenu?]]
- [[#what-is-dmenu-flexipatch][What is dmenu-flexipatch?]]
- [[#what-is-dmenu-1][What is dmenu]]
- [[#mouse-functionality][Mouse functionality]]
- [[#installing-dmenu-on-other-linux-distributions][Installing dmenu on other Linux distributions]]

* What is dmenu?
#+CAPTION: dmenu
#+ATTR_HTML: :alt dmenu :title dmenu :align left

dmenu is a dynamic menu for X, originally designed for dwm. It manages large numbers of user-defined menu items efficiently.  It is a very powerful tool that allows you to pipe information into it.  This makes dmenu a perfect utility to incorporate into your scripting.

* What is dmenu-flexipatch?
Similar to [[https://github.com/bakkeby/dwm-flexipatch][dwm-flexipatch]], the [[https://github.com/bakkeby/dmenu-flexipatch][dmenu-flexipatch]] project has a unique take on patching. It uses preprocessor directives to decide whether or not to include a patch during build time.  Patching with dmenu-flexipatch is much easier than the traditional patching methods, especially when using many patches (which I do!).

Patches can be added/removed using the patches.def.h file.  For example to include the `alpha` patch then you would only need to flip this setting from 0
to 1:
#+begin_example
#define ALPHA_PATCH 1
#+end_example

After you have decided on the patches that work for you, then run:
=sudo make install=

* What is dmenu
dmenu-distroube is my personal build of dmenu that is very heavily patched to add more functionality and more customization options.   I originally did this through traditional patching of the standard Suckless version of dmenu. The patches that I used were:
+ dmenu-alpha -- adds transparency as an option.
+ dmenu-fuzzyhighlight -- fuzzy matches gets highlighted
+ dmenu-fuzzymatch -- adds support for fuzzy-matching
+ dmenu-lineheight -- adds a flag (-h) to set the minimum height of dmenu lines
+ dmenu-mousesupport -- basic mouse support
+ dmenu-xresources -- allows colors to be set via Xresources

Due to the tedious nature of applying so many patches, I now use [[https://github.com/bakkeby/dmenu-flexipatch][dmenu-flexipatch]] for building dmenu.  After all, no need to reinvent the wheel!

* Mouse functionality
Mouse actions supported:
+ Left-mouse click:
  - On prompt and input field: clear input text and selection.
  - In horizontal and vertical mode on item: select and output item (same as pressing enter).
  - In horizontal mode on arrows: change items to show left or right.
+ Ctrl-left-mouse click: multisel modifier.
+ Right-mouse click: close.
+ Middle-mouse click:
  - Paste current selection.
  - While holding shift: paste primary selection.
+ Scroll up:
  - In horizontal mode: same as left-clicking on left arrow.
  - In vertical mode: show items above.
+ Scroll down:
  - In horizontal mode: same as left-clicking on right arrow.
  - In vertical mode: show items below.

* Installing dmenu on other Linux distributions
Download the source code from this repository or use a git clone:

+ git clone https://github.com/tzurita/dmenu.git
+ cd dmenu
+ sudo make clean install && rm config.h

=NOTE:= Installing dmenu will overwrite your existing dmenu installation so make a backup of your current config if you need it.
